### PR TITLE
Update Swift version to 5.0

### PR DESCRIPTION
**Pull request by okaverin**

### CODE REVIEW

**Comment by DivineDominion** [comment]
Could you add a line for your changes to the CHANGELOG, too? Also, you might want to skip ahead to ReSwift 5.0 while you're at it, which we're about to release this week :)

**Comment by DivineDominion** [comment]
@okaverin ReSwift 5 is ready, if you're still interested!

**Comment by elishaterada** [comment]
@okaverin I'd love to see Swift 5 and ReSwift 5 update!

**Comment by DivineDominion** [comment]
Closing this because, as @mjarvis pointed out in https://github.com/ReSwift/ReSwift/pull/414, there's no need to exclude Swift 4.2 users from using the lib with Carthage as long as they are source compatible.

**Pull request closed without merging**
