### PR TITLE
Carthage build error

### PR DESCRIPTION
**Pull request by DivineDominion**
I upgraded my machine to Catalina, Xcode to 11.5, and Carthage to 0.35.0 -- and now `ReSwift-Thunk` doesn't compile anymore because it doesn't find the proper ReSwift :)

```
*** Building scheme "ReSwift-Thunk" in ReSwift-Thunk.xcodeproj
/usr/bin/xcrun xcodebuild -project /Users/ctm/Downloads/test/Carthage/Checkouts/ReSwift-Thunk/ReSwift-Thunk.xcodeproj -scheme ReSwift-Thunk -configuration Release -derivedDataPath /Users/ctm/Library/Caches/org.carthage.CarthageKit/DerivedData/11.5_11E608c/ReSwift-Thunk/f5960f32ebda66021dbb35a87d2433d301c28908 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/ReSwift-Thunk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/ctm/Downloads/test/Carthage/Checkouts/ReSwift-Thunk)Command line invocation:
    /Applications/Xcode115.app/Contents/Developer/usr/bin/xcodebuild -project /Users/ctm/Downloads/test/Carthage/Checkouts/ReSwift-Thunk/ReSwift-Thunk.xcodeproj -scheme ReSwift-Thunk -configuration Release -derivedDataPath /Users/ctm/Library/Caches/org.carthage.CarthageKit/DerivedData/11.5_11E608c/ReSwift-Thunk/f5960f32ebda66021dbb35a87d2433d301c28908 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/ReSwift-Thunk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO

User defaults from command line:
    IDEArchivePathOverride = /var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/ReSwift-Thunk
    IDEDerivedDataPathOverride = /Users/ctm/Library/Caches/org.carthage.CarthageKit/DerivedData/11.5_11E608c/ReSwift-Thunk/f5960f32ebda66021dbb35a87d2433d301c28908

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

Build Preparation
Build task concurrency set to 5 via user default IDEBuildOperationMaxNumberOfConcurrentCompileTasks

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: Building for macOS, but the linked framework 'ReSwift.framework' was built for iOS + iOS Simulator. (in target 'ReSwift-Thunk' from project 'ReSwift-Thunk')
```

(Let's see what CI says)

### CODE REVIEW

**Comment by DivineDominion** [comment]
@mjarvis @dani-mp Can you have a look on your local machines? 🤔

```
$ cat Cartfile
github "ReSwift/ReSwift-Thunk" "master"

$ carthage bootstrap --platform "mac" --verbose
...
error: Building for macOS, but the linked framework 'ReSwift.framework' was built for iOS + iOS Simulator. (in target 'ReSwift-Thunk' from project 'ReSwift-Thunk')
```

I have the same problem when I open the ReSwift-Thunk Xcode project and try to build for Mac. iOS works fine, but Mac complains:

> Building for macOS, but the linked framework 'ReSwift.framework' was built for iOS + iOS Simulator.

I wonder if that's an Xcode bug or misconfiguration on our part.

**Comment by DivineDominion** [comment]
Also no dice with Xcode 11.6 beta

**Comment by mjarvis** [comment]
@DivineDominion CI should pass this time around, if you want to take a look at my updates before I merge and then release `2.0.1`.

I've tested this with `carthage.sh build --no-skip-current --archive` and it builds successfully.

**Comment by DivineDominion** [comment]
@mjarvis LGTM! Also, sorry I was too late with ReSwift yesterday and you had to figure out the carthage.sh stuff for yourself all over again.

**Review by mjarvis — APPROVED** [review]

**Pull request merged**
