### PR TITLE
add watchOS to Travis config

### PR DESCRIPTION
**Pull request by DivineDominion**

### CODE REVIEW

**Comment by DivineDominion** [comment]
I stumbled upon watchOS not building at all with Carthage. To make CI catch this stuff for us, I think this should be added first.

**Comment by DivineDominion** [comment]
@danielmartinprieto No need to bounce back after the review, go ahead and squash & merge if you find the config change works good enough

**Comment by dani-mp** [comment]
@DivineDominion cool, I will take a look if there is something else to be added. Have you checked the fix I made in the `implementation` branch? If you can confirm that it’s working we can create the PR and then try this one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DivineDominion** [comment]
No, I haven't noticed that. You can make a WIP PR from that so that at least Travis checks the builds on all platforms for us, after this here is merged.

**Pull request merged**
