### PR TITLE
add CocoaPods support

### PR DESCRIPTION
**Pull request by DivineDominion**
Halted until @danielmartinprieto figures out how to make Carthage work with the single target project setup, and we can tag a release as v1.0.0.

### CODE REVIEW

**Comment by DivineDominion** [comment]
@danielmartinprieto Sample project attached, in case you don't want to whip up your own :) 

1. To pass `pod spec lint`, I had to provide a release for this repo (called it `1.0.0-pre`). We need to change that once we're ready. When you merge this in, I do think you can already change it in the podspec to `1.0.0` again already if you want 🤔
2. I renamed the module to get rid of the underscore in `ReSwift_Thunk`.

[ThunkProj.zip](https://github.com/ReSwift/ReSwift-Thunk/files/2612148/ThunkProj.zip)

**Comment by DivineDominion** [comment]
Oh, and I'm not that experienced with pushing stuff to CocoaPods. Maybe we do have to add our names to the `authors` list in order to execute `pod trunk push` with our local sessions.

**Comment by dani-mp** [comment]
Hi! I’ve never pushed anything to Cocoapods before. Since Carthage came out I’ve pretty much used it for all my projects. I can check the authors thing when I have time and come back to you.

About the renaming, I rather keep it as it was. I think having called it ReSwift-Thunk was a mistake, but it’s all over the place now (the repo, the project name, etc.) To change all that, I think it’s better to start over, and if we don’t do it, we’re going to have a lot of inconsistencies. If we keep it as it was, it will be ReSwift-Thunk everywhere, and only to import it we have to use the underscore (which is unfortunate but hopefully we have autocomplete). What do you think, @DivineDominion?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DivineDominion** [comment]
Then I'll handle pushing to CocoaPods if you don't want to spend the time fiddling with the new environment 👍

I think the underscore is ugly as sin :) 

If the only place the `-` is not used is in import statement, and you argue that we have auto-completion to help, then calling the module `ReSwiftThunk` with neither `-` nor `_` is just as confusing, so there's no downside.

The `ReSwift-Router` repo calls the whole pod "ReSwiftRouter", not just the module, so no need to worry about naming inconsistencies :) https://github.com/ReSwift/ReSwift-Router/blob/master/ReSwiftRouter.podspec

`ReSwift-Recorder` does it in a similar fashion: https://github.com/ReSwift/ReSwift-Recorder/blob/master/ReSwiftRecorder.podspec

It's a far greater deviation to introduce an underscore in import lists like:

```swift
import ReSwift
import ReSwiftRecorder
import ReSwift_Thunk
import ReSwiftRouter
```

If you want to rename all project files and settings to get rid of the `-` everywhere, we can do that, too. There's no real release, yet, so we can still change things around. I'd like to keep the dash in the repo name, though, for consistency with the other repos.

**Comment by dani-mp** [comment]
@DivineDominion all right, I think it’s fine as you decided! Thanks for putting together the Cocoapods integration 🎉.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
